/*You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.*/
 
// Time Complexity (TC): O(n * m)
// Space Complexity (SC): O(n + m)
class Solution {
    bool isSame(string &word, string &str2, int start, int m) {
        for(int j = 0; j < m; j++) {
            if(start + j >= word.size() || word[start + j] != str2[j])
                return false;
        }
        return true;
    }

public:
    string generateString(string str1, string str2) {
        int n = str1.length();
        int m = str2.length();
        int N = n + m - 1;
        string word(N, '0');
        vector<bool> canChange(N, false);

        // Process 'T'
        for (int i = 0; i < n; i++) {
            if (str1[i] == 'T') {
                int pos = i;
                for (int j = 0; j < m; j++) {
                    if(word[pos] != '0' && word[pos] != str2[j])
                        return "";
                    word[pos] = str2[j];
                    pos++;
                }
            }
        }

        // Fill remaining spaces with 'a'
        for (int i = 0; i < N; i++) {
            if (word[i] == '0') {
                word[i] = 'a';
                canChange[i] = true;
            }
        }

        // Process 'F'
        for (int i = 0; i < n; i++) {
            if (str1[i] == 'F') {
                if (isSame(word, str2, i, m)) {
                    bool change = false;
                    for (int k = i + m - 1; k >= i; k--) {
                        if (canChange[k]) {
                            word[k] = 'b';
                            change = true;
                            break;
                        }
                    }
                    if (!change) return "";
                }
            }
        }

        return word;
    }
};
